#!/usr/bin/env python3
"""Regenerate testing/markup-test.html from a live cloud-function payload.

Renders the four TRMNL view sizes as static HTML so the markup can be previewed
in a browser. The <div class="view view--*"> wrapper added here is supplied by
the TRMNL platform in production — the .liquid source files must NOT include it.

Run from the repo root:  python testing/gen.py
"""

import html
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "src", "cloud-function"))

from trmnl import build_payload  # noqa: E402

ICON = "https://trmnl.com/images/plugins/trmnl--render.svg"


def esc(value: object) -> str:
    return html.escape(str(value))


def column(routes, max_cols, time_limit=None, dest_limit=None):
    out = [f'<div class="column" data-overflow-max-cols="{max_cols}" data-overflow-counter="true">']
    for route in routes:
        out.append(f'<div class="item"><div class="meta"><span class="index">{esc(route["line"])}</span></div><div class="content">')
        for dest in route["destinations"][:dest_limit]:
            platform = f' ({esc(dest["platform"])})' if dest["platform"] else ""
            out.append(f'<span class="title title--small" data-clamp="1">{esc(dest["destination"])}{platform}</span>')
            out.append('<div class="flex flex--row flex--wrap gap--small">')
            for time in dest["times"][:time_limit]:
                out.append(f'<span class="label label--small label--underline">{esc(time)}</span>')
            out.append('</div>')
        out.append('</div></div>')
    out.append('</div>')
    return "\n".join(out)


def view(cls, inner, station, instance):
    return f'''  <div class="screen">
    <div class="view {cls}">
      <div class="layout"><div class="columns">{inner}</div></div>
      <div class="title_bar">
        <img class="image" src="{ICON}">
        <span class="title" data-clamp="1">{station}</span>
        <span class="instance">{instance}</span>
      </div>
    </div>
  </div>'''


def main():
    payload = build_payload("NSR:StopPlace:58366", "", 30, 3)
    station = esc(payload["station"])
    subtitle = f'Next {payload["window_minutes"]} min · {payload["shown"]} dep · {payload["last_updated"]}'
    lines = payload["lines"]

    views = "\n".join([
        view("view--full", column(lines, 3), station, subtitle),
        view("view--half_vertical", column(lines, 1, time_limit=4), station, subtitle),
        view("view--half_horizontal", column(lines, 4, time_limit=3), station, subtitle),
        view("view--quadrant", column(lines, 1, time_limit=2, dest_limit=1), station, payload["last_updated"]),
    ])

    doc = f'''<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Norway departures — TRMNL preview</title>
  <link rel="stylesheet" href="https://usetrmnl.com/css/latest/plugins.css">
  <script src="https://usetrmnl.com/js/latest/plugins.js"></script>
</head>
<!-- Generated by testing/gen.py. Do not hand-edit. -->
<body class="environment trmnl">
{views}
</body>
</html>
'''
    out_path = os.path.join(ROOT, "testing", "markup-test.html")
    with open(out_path, "w") as fh:
        fh.write(doc)
    print(f"wrote {out_path}: {len(lines)} lines, {payload['shown']} departures")


if __name__ == "__main__":
    main()
